name: Flask CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-html unittest-xml-reporting
          pip install -r requirements.txt

      - name: Run unit tests and generate report
        run: |
          python -m xmlrunner discover -s . -p "test_app.py" -o test-reports

      - name: Upload Test Report (XML)
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test-reports
          
  docker-build:
    runs-on: ubuntu-latest
    needs: test  # Ensures tests pass before building

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run container and test it
        run: |
          docker run -d -p 8080:8080 --name flask-container flask-app
          sleep 5  # Wait for Flask to start
          curl --fail http://localhost:8080/
          curl --fail http://localhost:8080/how%20are%20you

      - name: Stop and remove container
        run: docker stop flask-container && docker rm flask-container