name: Flask CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Run Flask container
        run: docker run -d -p 8080:8080 --name flask-container flask-app

      - name: Wait for the app to start
        run: sleep 5

      - name: Test application response
        run: curl --fail http://localhost:8080

      - name: Stop and remove container
        run: docker stop flask-container && docker rm flask-container
